import { chromium } from "playwright-core";
const browser = await chromium.launch({ executablePath: "/Users/mac/Library/Caches/ms-playwright/chromium_headless_shell-1148/chrome-mac/headless_shell" });
const page = await (await browser.newContext()).newPage();
page.on("pageerror", e => console.log("PAGEERROR:", String(e).slice(0, 300)));
page.on("requestfailed", r => console.log("REQFAIL:", r.url().slice(0, 110), r.failure()?.errorText));
page.on("response", r => { if (!r.ok()) console.log("HTTP", r.status(), r.url().slice(0, 110)); });
await page.goto("https://nreservi.online/owner/login", { waitUntil: "networkidle" });
console.log("--- scripts on page ---");
console.log(await page.locator("script[src]").evaluateAll(els => els.map(e => e.getAttribute("src"))));
console.log("--- hydrated? ---");
console.log(await page.evaluate(() => Object.keys(window).filter(k => k.startsWith("$_TSR")).join(",") || "NO TSR"));
await browser.close();
