/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MyReservationsRouteImport } from './routes/my-reservations'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsSlugRouteImport } from './routes/restaurants.$slug'
import { Route as OwnerLoginRouteImport } from './routes/owner/login'
import { Route as OwnerAuthedRouteImport } from './routes/owner/_authed'
import { Route as R3991LoginRouteImport } from './routes/3991/login'
import { Route as R3991AuthedRouteImport } from './routes/3991/_authed'
import { Route as OwnerAuthedIndexRouteImport } from './routes/owner/_authed.index'
import { Route as R3991AuthedIndexRouteImport } from './routes/3991/_authed.index'
import { Route as OwnerAuthedSettingsRouteImport } from './routes/owner/_authed.settings'
import { Route as OwnerAuthedMenuRouteImport } from './routes/owner/_authed.menu'
import { Route as OwnerAuthedMarketingRouteImport } from './routes/owner/_authed.marketing'
import { Route as OwnerAuthedBillingRouteImport } from './routes/owner/_authed.billing'
import { Route as OwnerAuthedAnalyticsRouteImport } from './routes/owner/_authed.analytics'
import { Route as R3991AuthedSubscriptionsRouteImport } from './routes/3991/_authed.subscriptions'
import { Route as R3991AuthedOnboardRouteImport } from './routes/3991/_authed.onboard'
import { Route as R3991AuthedMailRouteImport } from './routes/3991/_authed.mail'
import { Route as R3991AuthedLogsRouteImport } from './routes/3991/_authed.logs'
import { Route as R3991AuthedLandingRouteImport } from './routes/3991/_authed.landing'
import { Route as R3991AuthedEmailsRouteImport } from './routes/3991/_authed.emails'
import { Route as R3991AuthedAdsRouteImport } from './routes/3991/_authed.ads'
import { Route as R3991AuthedAccountRouteImport } from './routes/3991/_authed.account'
import { Route as OwnerAuthedSettingsWhatsappRouteImport } from './routes/owner/_authed.settings_.whatsapp'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReservationsRoute = MyReservationsRouteImport.update({
  id: '/my-reservations',
  path: '/my-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsSlugRoute = RestaurantsSlugRouteImport.update({
  id: '/restaurants/$slug',
  path: '/restaurants/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAuthedRoute = OwnerAuthedRouteImport.update({
  id: '/owner/_authed',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const R3991LoginRoute = R3991LoginRouteImport.update({
  id: '/3991/login',
  path: '/3991/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R3991AuthedRoute = R3991AuthedRouteImport.update({
  id: '/3991/_authed',
  path: '/3991',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAuthedIndexRoute = OwnerAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const R3991AuthedIndexRoute = R3991AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R3991AuthedRoute,
} as any).lazy(() =>
  import('./routes/3991/_authed.index.lazy').then((d) => d.Route),
)
const OwnerAuthedSettingsRoute = OwnerAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const OwnerAuthedMenuRoute = OwnerAuthedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const OwnerAuthedMarketingRoute = OwnerAuthedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const OwnerAuthedBillingRoute = OwnerAuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OwnerAuthedRoute,
} as any)
const OwnerAuthedAnalyticsRoute = OwnerAuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OwnerAuthedRoute,
} as any).lazy(() =>
  import('./routes/owner/_authed.analytics.lazy').then((d) => d.Route),
)
const R3991AuthedSubscriptionsRoute =
  R3991AuthedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => R3991AuthedRoute,
  } as any)
const R3991AuthedOnboardRoute = R3991AuthedOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => R3991AuthedRoute,
} as any)
const R3991AuthedMailRoute = R3991AuthedMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => R3991AuthedRoute,
} as any)
const R3991AuthedLogsRoute = R3991AuthedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => R3991AuthedRoute,
} as any)
const R3991AuthedLandingRoute = R3991AuthedLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => R3991AuthedRoute,
} as any)
const R3991AuthedEmailsRoute = R3991AuthedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => R3991AuthedRoute,
} as any)
const R3991AuthedAdsRoute = R3991AuthedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => R3991AuthedRoute,
} as any)
const R3991AuthedAccountRoute = R3991AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => R3991AuthedRoute,
} as any)
const OwnerAuthedSettingsWhatsappRoute =
  OwnerAuthedSettingsWhatsappRouteImport.update({
    id: '/settings_/whatsapp',
    path: '/settings/whatsapp',
    getParentRoute: () => OwnerAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/my-reservations': typeof MyReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/3991': typeof R3991AuthedRouteWithChildren
  '/3991/login': typeof R3991LoginRoute
  '/owner': typeof OwnerAuthedRouteWithChildren
  '/owner/login': typeof OwnerLoginRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/3991/account': typeof R3991AuthedAccountRoute
  '/3991/ads': typeof R3991AuthedAdsRoute
  '/3991/emails': typeof R3991AuthedEmailsRoute
  '/3991/landing': typeof R3991AuthedLandingRoute
  '/3991/logs': typeof R3991AuthedLogsRoute
  '/3991/mail': typeof R3991AuthedMailRoute
  '/3991/onboard': typeof R3991AuthedOnboardRoute
  '/3991/subscriptions': typeof R3991AuthedSubscriptionsRoute
  '/owner/analytics': typeof OwnerAuthedAnalyticsRoute
  '/owner/billing': typeof OwnerAuthedBillingRoute
  '/owner/marketing': typeof OwnerAuthedMarketingRoute
  '/owner/menu': typeof OwnerAuthedMenuRoute
  '/owner/settings': typeof OwnerAuthedSettingsRoute
  '/3991/': typeof R3991AuthedIndexRoute
  '/owner/': typeof OwnerAuthedIndexRoute
  '/owner/settings/whatsapp': typeof OwnerAuthedSettingsWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/my-reservations': typeof MyReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/3991/login': typeof R3991LoginRoute
  '/owner/login': typeof OwnerLoginRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/3991/account': typeof R3991AuthedAccountRoute
  '/3991/ads': typeof R3991AuthedAdsRoute
  '/3991/emails': typeof R3991AuthedEmailsRoute
  '/3991/landing': typeof R3991AuthedLandingRoute
  '/3991/logs': typeof R3991AuthedLogsRoute
  '/3991/mail': typeof R3991AuthedMailRoute
  '/3991/onboard': typeof R3991AuthedOnboardRoute
  '/3991/subscriptions': typeof R3991AuthedSubscriptionsRoute
  '/owner/analytics': typeof OwnerAuthedAnalyticsRoute
  '/owner/billing': typeof OwnerAuthedBillingRoute
  '/owner/marketing': typeof OwnerAuthedMarketingRoute
  '/owner/menu': typeof OwnerAuthedMenuRoute
  '/owner/settings': typeof OwnerAuthedSettingsRoute
  '/3991': typeof R3991AuthedIndexRoute
  '/owner': typeof OwnerAuthedIndexRoute
  '/owner/settings/whatsapp': typeof OwnerAuthedSettingsWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/my-reservations': typeof MyReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/3991/_authed': typeof R3991AuthedRouteWithChildren
  '/3991/login': typeof R3991LoginRoute
  '/owner/_authed': typeof OwnerAuthedRouteWithChildren
  '/owner/login': typeof OwnerLoginRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/3991/_authed/account': typeof R3991AuthedAccountRoute
  '/3991/_authed/ads': typeof R3991AuthedAdsRoute
  '/3991/_authed/emails': typeof R3991AuthedEmailsRoute
  '/3991/_authed/landing': typeof R3991AuthedLandingRoute
  '/3991/_authed/logs': typeof R3991AuthedLogsRoute
  '/3991/_authed/mail': typeof R3991AuthedMailRoute
  '/3991/_authed/onboard': typeof R3991AuthedOnboardRoute
  '/3991/_authed/subscriptions': typeof R3991AuthedSubscriptionsRoute
  '/owner/_authed/analytics': typeof OwnerAuthedAnalyticsRoute
  '/owner/_authed/billing': typeof OwnerAuthedBillingRoute
  '/owner/_authed/marketing': typeof OwnerAuthedMarketingRoute
  '/owner/_authed/menu': typeof OwnerAuthedMenuRoute
  '/owner/_authed/settings': typeof OwnerAuthedSettingsRoute
  '/3991/_authed/': typeof R3991AuthedIndexRoute
  '/owner/_authed/': typeof OwnerAuthedIndexRoute
  '/owner/_authed/settings_/whatsapp': typeof OwnerAuthedSettingsWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/my-reservations'
    | '/reset-password'
    | '/terms'
    | '/3991'
    | '/3991/login'
    | '/owner'
    | '/owner/login'
    | '/restaurants/$slug'
    | '/3991/account'
    | '/3991/ads'
    | '/3991/emails'
    | '/3991/landing'
    | '/3991/logs'
    | '/3991/mail'
    | '/3991/onboard'
    | '/3991/subscriptions'
    | '/owner/analytics'
    | '/owner/billing'
    | '/owner/marketing'
    | '/owner/menu'
    | '/owner/settings'
    | '/3991/'
    | '/owner/'
    | '/owner/settings/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/my-reservations'
    | '/reset-password'
    | '/terms'
    | '/3991/login'
    | '/owner/login'
    | '/restaurants/$slug'
    | '/3991/account'
    | '/3991/ads'
    | '/3991/emails'
    | '/3991/landing'
    | '/3991/logs'
    | '/3991/mail'
    | '/3991/onboard'
    | '/3991/subscriptions'
    | '/owner/analytics'
    | '/owner/billing'
    | '/owner/marketing'
    | '/owner/menu'
    | '/owner/settings'
    | '/3991'
    | '/owner'
    | '/owner/settings/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/forgot-password'
    | '/my-reservations'
    | '/reset-password'
    | '/terms'
    | '/3991/_authed'
    | '/3991/login'
    | '/owner/_authed'
    | '/owner/login'
    | '/restaurants/$slug'
    | '/3991/_authed/account'
    | '/3991/_authed/ads'
    | '/3991/_authed/emails'
    | '/3991/_authed/landing'
    | '/3991/_authed/logs'
    | '/3991/_authed/mail'
    | '/3991/_authed/onboard'
    | '/3991/_authed/subscriptions'
    | '/owner/_authed/analytics'
    | '/owner/_authed/billing'
    | '/owner/_authed/marketing'
    | '/owner/_authed/menu'
    | '/owner/_authed/settings'
    | '/3991/_authed/'
    | '/owner/_authed/'
    | '/owner/_authed/settings_/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MyReservationsRoute: typeof MyReservationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  R3991AuthedRoute: typeof R3991AuthedRouteWithChildren
  R3991LoginRoute: typeof R3991LoginRoute
  OwnerAuthedRoute: typeof OwnerAuthedRouteWithChildren
  OwnerLoginRoute: typeof OwnerLoginRoute
  RestaurantsSlugRoute: typeof RestaurantsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reservations': {
      id: '/my-reservations'
      path: '/my-reservations'
      fullPath: '/my-reservations'
      preLoaderRoute: typeof MyReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$slug': {
      id: '/restaurants/$slug'
      path: '/restaurants/$slug'
      fullPath: '/restaurants/$slug'
      preLoaderRoute: typeof RestaurantsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/_authed': {
      id: '/owner/_authed'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3991/login': {
      id: '/3991/login'
      path: '/3991/login'
      fullPath: '/3991/login'
      preLoaderRoute: typeof R3991LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3991/_authed': {
      id: '/3991/_authed'
      path: '/3991'
      fullPath: '/3991'
      preLoaderRoute: typeof R3991AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/_authed/': {
      id: '/owner/_authed/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerAuthedIndexRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/3991/_authed/': {
      id: '/3991/_authed/'
      path: '/'
      fullPath: '/3991/'
      preLoaderRoute: typeof R3991AuthedIndexRouteImport
      parentRoute: typeof R3991AuthedRoute
    }
    '/owner/_authed/settings': {
      id: '/owner/_authed/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerAuthedSettingsRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/owner/_authed/menu': {
      id: '/owner/_authed/menu'
      path: '/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof OwnerAuthedMenuRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/owner/_authed/marketing': {
      id: '/owner/_authed/marketing'
      path: '/marketing'
      fullPath: '/owner/marketing'
      preLoaderRoute: typeof OwnerAuthedMarketingRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/owner/_authed/billing': {
      id: '/owner/_authed/billing'
      path: '/billing'
      fullPath: '/owner/billing'
      preLoaderRoute: typeof OwnerAuthedBillingRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/owner/_authed/analytics': {
      id: '/owner/_authed/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAuthedAnalyticsRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
    '/3991/_authed/subscriptions': {
      id: '/3991/_authed/subscriptions'
      path: '/subscriptions'
      fullPath: '/3991/subscriptions'
      preLoaderRoute: typeof R3991AuthedSubscriptionsRouteImport
      parentRoute: typeof R3991AuthedRoute
    }
    '/3991/_authed/onboard': {
      id: '/3991/_authed/onboard'
      path: '/onboard'
      fullPath: '/3991/onboard'
      preLoaderRoute: typeof R3991AuthedOnboardRouteImport
      parentRoute: typeof R3991AuthedRoute
    }
    '/3991/_authed/mail': {
      id: '/3991/_authed/mail'
      path: '/mail'
      fullPath: '/3991/mail'
      preLoaderRoute: typeof R3991AuthedMailRouteImport
      parentRoute: typeof R3991AuthedRoute
    }
    '/3991/_authed/logs': {
      id: '/3991/_authed/logs'
      path: '/logs'
      fullPath: '/3991/logs'
      preLoaderRoute: typeof R3991AuthedLogsRouteImport
      parentRoute: typeof R3991AuthedRoute
    }
    '/3991/_authed/landing': {
      id: '/3991/_authed/landing'
      path: '/landing'
      fullPath: '/3991/landing'
      preLoaderRoute: typeof R3991AuthedLandingRouteImport
      parentRoute: typeof R3991AuthedRoute
    }
    '/3991/_authed/emails': {
      id: '/3991/_authed/emails'
      path: '/emails'
      fullPath: '/3991/emails'
      preLoaderRoute: typeof R3991AuthedEmailsRouteImport
      parentRoute: typeof R3991AuthedRoute
    }
    '/3991/_authed/ads': {
      id: '/3991/_authed/ads'
      path: '/ads'
      fullPath: '/3991/ads'
      preLoaderRoute: typeof R3991AuthedAdsRouteImport
      parentRoute: typeof R3991AuthedRoute
    }
    '/3991/_authed/account': {
      id: '/3991/_authed/account'
      path: '/account'
      fullPath: '/3991/account'
      preLoaderRoute: typeof R3991AuthedAccountRouteImport
      parentRoute: typeof R3991AuthedRoute
    }
    '/owner/_authed/settings_/whatsapp': {
      id: '/owner/_authed/settings_/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/owner/settings/whatsapp'
      preLoaderRoute: typeof OwnerAuthedSettingsWhatsappRouteImport
      parentRoute: typeof OwnerAuthedRoute
    }
  }
}

interface R3991AuthedRouteChildren {
  R3991AuthedAccountRoute: typeof R3991AuthedAccountRoute
  R3991AuthedAdsRoute: typeof R3991AuthedAdsRoute
  R3991AuthedEmailsRoute: typeof R3991AuthedEmailsRoute
  R3991AuthedLandingRoute: typeof R3991AuthedLandingRoute
  R3991AuthedLogsRoute: typeof R3991AuthedLogsRoute
  R3991AuthedMailRoute: typeof R3991AuthedMailRoute
  R3991AuthedOnboardRoute: typeof R3991AuthedOnboardRoute
  R3991AuthedSubscriptionsRoute: typeof R3991AuthedSubscriptionsRoute
  R3991AuthedIndexRoute: typeof R3991AuthedIndexRoute
}

const R3991AuthedRouteChildren: R3991AuthedRouteChildren = {
  R3991AuthedAccountRoute: R3991AuthedAccountRoute,
  R3991AuthedAdsRoute: R3991AuthedAdsRoute,
  R3991AuthedEmailsRoute: R3991AuthedEmailsRoute,
  R3991AuthedLandingRoute: R3991AuthedLandingRoute,
  R3991AuthedLogsRoute: R3991AuthedLogsRoute,
  R3991AuthedMailRoute: R3991AuthedMailRoute,
  R3991AuthedOnboardRoute: R3991AuthedOnboardRoute,
  R3991AuthedSubscriptionsRoute: R3991AuthedSubscriptionsRoute,
  R3991AuthedIndexRoute: R3991AuthedIndexRoute,
}

const R3991AuthedRouteWithChildren = R3991AuthedRoute._addFileChildren(
  R3991AuthedRouteChildren,
)

interface OwnerAuthedRouteChildren {
  OwnerAuthedAnalyticsRoute: typeof OwnerAuthedAnalyticsRoute
  OwnerAuthedBillingRoute: typeof OwnerAuthedBillingRoute
  OwnerAuthedMarketingRoute: typeof OwnerAuthedMarketingRoute
  OwnerAuthedMenuRoute: typeof OwnerAuthedMenuRoute
  OwnerAuthedSettingsRoute: typeof OwnerAuthedSettingsRoute
  OwnerAuthedIndexRoute: typeof OwnerAuthedIndexRoute
  OwnerAuthedSettingsWhatsappRoute: typeof OwnerAuthedSettingsWhatsappRoute
}

const OwnerAuthedRouteChildren: OwnerAuthedRouteChildren = {
  OwnerAuthedAnalyticsRoute: OwnerAuthedAnalyticsRoute,
  OwnerAuthedBillingRoute: OwnerAuthedBillingRoute,
  OwnerAuthedMarketingRoute: OwnerAuthedMarketingRoute,
  OwnerAuthedMenuRoute: OwnerAuthedMenuRoute,
  OwnerAuthedSettingsRoute: OwnerAuthedSettingsRoute,
  OwnerAuthedIndexRoute: OwnerAuthedIndexRoute,
  OwnerAuthedSettingsWhatsappRoute: OwnerAuthedSettingsWhatsappRoute,
}

const OwnerAuthedRouteWithChildren = OwnerAuthedRoute._addFileChildren(
  OwnerAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MyReservationsRoute: MyReservationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  R3991AuthedRoute: R3991AuthedRouteWithChildren,
  R3991LoginRoute: R3991LoginRoute,
  OwnerAuthedRoute: OwnerAuthedRouteWithChildren,
  OwnerLoginRoute: OwnerLoginRoute,
  RestaurantsSlugRoute: RestaurantsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
